name: Build ROMs
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-roms:
    name: Build ROMs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install GBDK-2020
        run: |
          wget https://github.com/gbdk-2020/gbdk-2020/releases/latest/download/gbdk-linux64.tar.gz
          tar -xzf gbdk-linux64.tar.gz
          rm gbdk-linux64.tar.gz
          mv gbdk ~
      - name: Build ROMs
        run: |
          make
      - name: Upload ROMs to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ROMs
          path: build
      - name: Generate pre-release tag
        id: tag
        # Only publish pre-release if the CI is running for a push of a branch and not for a tag
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          echo "::set-output name=prerelease_id::$(date +"%Y-%m-%dT%H%M")"
      - name: Generate release notes
        id: notes
        run: |
          git fetch --unshallow
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=release_notes::$(git log $latest_tag..HEAD --oneline --no-merges --pretty=format:'* %s in commit %h')"
      - name: Publish pre-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Only publish pre-release if the CI is running for a push of a branch and not for a tag
        if: startsWith(github.ref, 'refs/heads/')
        with:
          name: 'Nightly ${{ steps.tag.outputs.prerelease_id }}'
          tag_name: 'nightly-${{ steps.tag.outputs.prerelease_id }}'
          body: |
            ## What's Changed
            ${{ steps.notes.outputs.release_notes }}
          prerelease: true
          files: |
            build/gb/portfolio.gb
            build/gbc/portfolio.gbc
            build/pocket/portfolio.pocket
            build/duck/portfolio.duck
