name: Build ROMs
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-roms:
    name: Build ROMs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install GBDK-2020
        run: |
          wget https://github.com/gbdk-2020/gbdk-2020/releases/latest/download/gbdk-linux64.tar.gz
          tar -xzf gbdk-linux64.tar.gz
          rm gbdk-linux64.tar.gz
          mv gbdk ~
      - name: Build ROMs
        run: |
          make
      - name: Upload ROMs to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ROMs
          path: build
      - name: Publish pre-release
        uses: softprops/action-gh-release@v1
        # Only publish pre-release if the CI is running for a push of a branch and not for a tag
        if: startsWith(github.ref, 'refs/heads/')
        with:
          prerelease: true
          generate_release_notes: true
          name: 'Build #${github.run_id}-${github.run_attempt}'
          files: |
            build/gb/portfolio.gb
            build/gbc/portfolio.gbc
            build/pocket/portfolio.pocket
            build/duck/portfolio.duck
